=== mateocrespi-design/Tarea4_LSMG/Ejercicio1/cifp.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

    <xs:simpleType name="tipusCurs">
        <xs:restriction base="xs:string">
            <xs:enumeration value="DAM"/>
            <xs:enumeration value="DAW"/>
            <xs:enumeration value="ASIX"/>
            <xs:enumeration value="SMX"/>
            <xs:enumeration value="SEIA"/>
            <xs:enumeration value="ER"/>
            <xs:enumeration value="AUT"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="tipusDepartament">
        <xs:restriction base="xs:string">
            <xs:enumeration value="Informàtica"/>
            <xs:enumeration value="Electricitat"/>
            <xs:enumeration value="Automoció"/>
        </xs:restriction>
    </xs:simpleType>

    <xs:complexType name="tipusNomAssignatura">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="cicle" type="tipusCurs" use="required"/>
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:complexType name="tipusAssignatura">
        <xs:sequence>
            <xs:element name="nom_assignatura" type="tipusNomAssignatura"/>
            <xs:element name="data_inici" type="xs:string" minOccurs="0"/>
            <xs:element name="data_final" type="xs:string" minOccurs="0"/>
        </xs:sequence>
        <xs:attribute name="id_assignatura" type="xs:integer" use="required"/>
    </xs:complexType>

    <xs:group name="dadesComunes">
        <xs:sequence>
            <xs:element name="nom" type="xs:string"/>
            <xs:element name="llinatges" type="xs:string"/>
            <xs:element name="data_naixement" type="xs:string" minOccurs="0"/>
            <xs:element name="correu" type="xs:string" minOccurs="0"/>
            <xs:element name="telefon" type="xs:string" minOccurs="0"/>
            <xs:element name="adreça" type="xs:string" minOccurs="0"/>
        </xs:sequence>
    </xs:group>

    <xs:element name="cifp">
        <xs:complexType>
            <xs:choice maxOccurs="unbounded">
                
                <xs:element name="alumne">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="dadesComunes"/>
                            <xs:element name="data_matricula" type="xs:string"/>
                            <xs:element name="curs" type="tipusCurs"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>

                <xs:element name="professor">
                    <xs:complexType>
                        <xs:sequence>
                            <xs:group ref="dadesComunes"/>
                            <xs:element name="data_incorporació" type="xs:string"/>
                            <xs:element name="departament" type="tipusDepartament"/>
                            <xs:element name="assignatura" type="tipusAssignatura" minOccurs="0" maxOccurs="unbounded"/>
                        </xs:sequence>
                        <xs:attribute name="id" type="xs:integer" use="required"/>
                    </xs:complexType>
                </xs:element>

            </xs:choice>
        </xs:complexType>
    </xs:element>

</xs:schema>

=== mateocrespi-design/Tarea4_LSMG/Ejercicio1/cifp_xsd.xml
<?xml version="1.0" encoding="UTF-8"?>
<cifp xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:noNamespaceSchemaLocation="cifp.xsd">
    
    <alumne id="202">
        <nom>Pere</nom>
        <llinatges>Martorell</llinatges>
        <data_matricula>12-09-2023</data_matricula>
        <curs>ASIX</curs>
    </alumne>

    <professor id="890">
        <nom>Laura</nom>
        <llinatges>Vidal</llinatges>
        <correu>laura.vidal@paucasesnoves.cat</correu>
        <data_incorporació>01-09-2020</data_incorporació>
        <departament>Automoció</departament>
        <assignatura id_assignatura="33">
            <nom_assignatura cicle="AUT">Motors Tèrmics</nom_assignatura>
            <data_inici>15-09-2023</data_inici>
        </assignatura>
    </professor>
</cifp>
